### PR TITLE
Revert "Ensure converter_path only throws NoPath exceptions"

### PR DESCRIPTION
**Pull request by danlamanna**
This reverts commit 7826b1c1e938eae106912c7ba974afc4348ea908.

### CODE REVIEW

**Comment by zachmullen** [comment]
This should solve the issue when an invalid type/format tuple is passed. How does the error message look if we try to convert between valid types and formats that simply don't have a conversion path?

**Comment by zachmullen** [comment]
LGTM

**Comment by cdeepakroy** [comment]
LGTM

**Comment by danlamanna** [comment]
@zachmullen [These tests](https://github.com/girder/girder_worker/pull/34/files#diff-bb295d0a4f0f6a658595c1ed65a2da3bR53) should explain what I updated. Errors for missing validators, missing paths, both of which include the id/name if used from run.

**Comment by zachmullen** [comment]
LGTM

**Pull request merged**
