### PR TITLE
Task cancellation using revoke

### PR DESCRIPTION
**Pull request by cjh1**
This sister PR in Girder is girder/girder#1983

### CODE REVIEW

**Comment by kotfic** [comment]
@cjh1 just as an FYI,  I am also introducing a base class in https://github.com/girder/girder_worker/pull/126

**Comment by cjh1** [comment]
@kotfic  Excellent :+1:

**Comment by cjh1** [comment]
@girder/developers This is ready for review, PTAL

**Comment by cjh1** [comment]
@kotfic PTAL at cdace94 where I have added some tests that use the new framework. These tests will currently fail as they need a specific girder branch.

**Comment by cjh1** [comment]
@kotfic @zachmullen Conflicts resolved. Note that the test failures are expected as this branch requires a corresponding girder branch and we can currently only test against master.

**Comment by cjh1** [comment]
@zachmullen So in item_tasks the state transitions are queued -> running  -> fetch input -> running?

**Comment by zachmullen** [comment]
item_tasks is just regular old docker tasks, so that transition is coming from the worker itself.

**Comment by cjh1** [comment]
OK, let me push a change that allows fetching input -> running.

**Comment by zachmullen** [comment]
It used to be the case that it went from Queued -> Fetching Input -> Running -> Pushing Output -> Success, but I think one of Chris K's refactors changed it and added the intermediate running state. Given that it is technically correct, it seemed OK, but I think the old way (just one running phase) would be preferable.

**Comment by zachmullen** [comment]
That's probably out of scope for this PR, though.

**Comment by cjh1** [comment]
@zachmullen I agree, one of the advances of enforcing these state transitions, is that in the future we will have to make a concussion decision to change them in the future. I have pushed a change that allows fetching input back to running.

**Comment by zachmullen** [comment]
@kotfic can still provide final approval, but I've tested this and it now works.

**Comment by zachmullen** [comment]
The integration test is failing, looks like it's simply expecting the wrong state transitions.

**Comment by cjh1** [comment]
@zachmullen As mentioned above. This branch is tied to #girder/girder/pull/1983, the integration test on Circle use girder master, so these failure are expected. Or did you run them locally?

**Comment by zachmullen** [comment]
Oh, I see. I'm going to go ahead and merge this. We'll merge the Girder side later and if anything breaks beyond that we'll fix it then.

Thanks for the extreme dedication on this PR @cjh1 !

**Comment by mgrauer** [comment]
💜 🚜

**Comment by zachmullen** [comment]
And I'm really hesitant to google "love tractor"

**Comment by cjh1** [comment]
Definitely a search to do on a colleagues computer :-)

**Comment by mgrauer** [comment]
This branch took a lot of time and maintenance and merging of master to push through, so I thought @cjh1 deserved a purple heart for his efforts, and he continued to plow through no matter what the difficulty, hence the tractor.

Surpringly, [Love Tractor](https://en.wikipedia.org/wiki/Love_Tractor) is SFW.

>Love Tractor (1980–2002) a band from Athens, Georgia, founded in spring 1980 by guitarists Mark Cline, Mike Richmond and bassist Armistead Wellford. Like The B-52's, Pylon and R.E.M., Love Tractor is lauded by critics and music historians as one of the founders of the Athens, Georgia, alternative rock scene. Love Tractor toured extensively and recorded six critically acclaimed albums, consistently topping the college and alternative charts. Love Tractor was particularly known for their instrumental rock.[1]

**Pull request merged**
