### PR TITLE
Fix EBADF errors

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by zachmullen** [comment]
EBADF refers to the python principle of "it's Easier to Beg Absolution than Die in Fire"

**Comment by cjh1** [comment]
:smile:

**Comment by zachmullen** [comment]
Is this intended to fix the py3_integration_tests?

**Comment by cjh1** [comment]
Take that Travis!

**Comment by mgrauer** [comment]
@cjh1 Can you add a short summary of what this PR is about? Thanks

**Comment by cjh1** [comment]
@mgrauer I added a description, hope that helps.

**Pull request merged**
