### PR TITLE
Call cleanup on girder_result_hook transforms. Fixes #348

### LINKED ISSUE #348: girder_result_hooks cleanup methods are not called after task is done
Hello everyone,

There seems to be an issue with task cleanup. The cleanup methods for transforms in args and kwargs are being called properly at the end of the task, but that is not the case for transforms in girder_result_hooks. Is this intended ?

This means for instance that when passing GirderUploadToItem in girder_result_hooks with the delete_file flag as True, the file is never deleted.

I'm pushing a potential fix for this issue:
https://github.com/girder/girder_worker/pull/349

### PR DESCRIPTION
**Pull request by boucaud**
https://github.com/girder/girder_worker/issues/348

### CODE REVIEW

**Comment by kotfic** [comment]
Yeah this looks good to me,  thanks for the fix!

**Comment by kotfic** [comment]
@boucaud Sorry looks like we neglected to turn on CircleCI for forked PRs,  could you push a new commit to trigger?  Thanks!

**Comment by zachmullen** [comment]
`git commit -m "kick CI" --allow-empty` should work

**Comment by boucaud** [comment]
These CI failures don't seem related, WDYT ?

**Comment by kotfic** [comment]
definitely not your issue,  its an issue with code coverage major version mismatch in the tox file and requirements*.txt file.  I am seeing if I can run down the "right" solution before I pin coverage<5.0.0

**Comment by kotfic** [comment]
Hi @boucaud,  I've updated the testing in master to resolve the coverage issue.  Can you rebase on master?  Thanks for hanging in there!

**Comment by boucaud** [comment]
Seems fine now, thanks !

**Comment by zachmullen** [comment]
Thanks for the fix @boucaud !

**Pull request merged**
