### PR TITLE
Streaming inputs

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by jcfr** [comment]
:+1

**Comment by zachmullen** [comment]
This is now working against the current https://github.com/zachmullen/docker_test

**Comment by jeffbaumes** [comment]
I'm having trouble doing the streaming test to QA the PR. Was the process documented somewhere on how to use https://github.com/zachmullen/docker_test and what I'm expected to see?

**Comment by zachmullen** [comment]
It was not documented, but here it is:

1. `vagrant up` the docker_test repo
2. Go to localhost:8080, upload an item that is plaintext and contains a reasonable number of newlines, like a CSV file.
3. Get the ID of the item, use it in the `POST docker_test/stream` endpoint.
4. Go back to localhost:8080, you should see a series of notifications coming in that have been artificially spaced out over time. The messages in these notifications should be each line of your input file, but reversed. (The actual script being run is [this](https://github.com/zachmullen/docker_test/blob/master/test.py)).

**Comment by jeffbaumes** [comment]
From a fresh vagrant up, and try that endpoint on an item with a CSV attached, I get a single notification saying "Docker stream demo" that does not go away or report anything else. I this in `worker.log` after doing vagrant ssh:

```
Error: No such image: testoutputs:latest
```

**Comment by jeffbaumes** [comment]
Found commented out line at the end of your ansible playbook that creates the docker container. Once I ran that, looks like it is working now! It went through the lines of the CSV file, then turns green and fades out.

LGTM

**Comment by zachmullen** [comment]
Thanks for the QA!

**Pull request merged**
