### PR TITLE
Remove requirements unpinning in setup.py

### PR DESCRIPTION
**Pull request by jbeezley**
This removes the dubious `unpin_version` function from `setup.py`.  In its place, the main requirements file used on travis is autogenerated using [pip-tools](https://github.com/jazzband/pip-tools).  I also fixed up the `scripts/install_requirements.py` script with a compatible interface that shouldn't be subject to the same kind of errors that have shown up in CI recently (https://github.com/girder/girder_worker/pull/198).

### CODE REVIEW

**Comment by cjh1** [comment]
@jbeezley Ok, good to know, can we merge this?

**Comment by cjh1** [comment]
@jbeezley I merged master in to resolve the conflict I caused!

**Comment by cjh1** [comment]
I plan on merging this unless anyone has any objections? @jbeezley @danlamanna @kotfic @dorukozturk

**Comment by jbeezley** [comment]
That's fine I was in a plane all day.  :P

**Pull request merged**
