### PR TITLE
Added format named string to string type

### PR DESCRIPTION
**Pull request by cdeepakroy**
This addresses concerns mentioned in issue #33 and #32.

### CODE REVIEW

**Comment by cdeepakroy** [comment]
CC: @zachmullen @jeffbaumes @danlamanna

**Comment by zachmullen** [comment]
I'm OK with this

**Comment by jeffbaumes** [comment]
Looking great. Just to avoid some code duplication, we should actually be able to remove the text_to_json and json_to_text json/py files and everything should still be able to work since the conversion would just step through the text <-> string conversion.

**Comment by cdeepakroy** [comment]
Oh yeah! since it tries the conversion path through the types. Thanks jeff.

Will merge after TravisCI shows a green flag.

**Comment by jeffbaumes** [comment]
Ha. Looks like of all things we were testing the path length of `string/text` to `string/json` and getting this error on Travis. I'll push a fix for the test (change the 1 to a 2).

```
9: Test timeout computed to be: 600
9: test_conversion_graph (tests.format_test.TestFormat) ... ok
9: test_conversion_table (tests.format_test.TestFormat) ... ok
9: test_converter_path (tests.format_test.TestFormat) ... FAIL
9: test_has_converter (tests.format_test.TestFormat) ... ok
9: test_is_valid (tests.format_test.TestFormat) ... ok
9: 
9: ======================================================================
9: FAIL: test_converter_path (tests.format_test.TestFormat)
9: ----------------------------------------------------------------------
9: Traceback (most recent call last):
9:   File "tests/format_test.py", line 35, in test_converter_path
9:     Validator('string', 'json'))), 1)
9: AssertionError: 2 != 1
9: 
9: ----------------------------------------------------------------------
9: Ran 5 tests in 0.017s
9: 
9: FAILED (failures=1)
 3/38 Test  #9: format ..................................***Failed    1.21 sec
```

**Comment by jeffbaumes** [comment]
LGTM

**Comment by cdeepakroy** [comment]
@jeffbaumes thanks for the fix.

**Pull request merged**
