### PR TITLE
Fail to start if exception occurs during plugin load

### LINKED ISSUE #360: Exceptions are silently ignored during plugin load
If an exception happens on the worker during plugin load time, the traceback of the exception is not printed as expected on [this line](https://github.com/girder/girder_worker/blob/df00a6f9ffa6d325bcb03a95793858d87fc22704/girder_worker/entrypoint.py#L55).

The message `Problem loading plugin mouse_pain_worker, skipping` does appear.

### PR DESCRIPTION
**Pull request by zachmullen**
Fixes #360

@kotfic PTAL. I guess celery is doing some dark magic monkey patching of `print` and standard pipes...

### CODE REVIEW

**Comment by zachmullen** [comment]
Looks like a test was depending on the wrong behavior. I will try to fix it up later I guess.

**Comment by zachmullen** [comment]
I'm not convinced we should start up if there's an exception during load. Would anyone actually defend that feature?

**Comment by kotfic** [comment]
I think the intention was to allow multiple plugins to be installed and if one fails to not cripple the whole system.  In reality though I think you're probably right,  plugin failure should probably cause a full stop and loudly complain.

**Comment by zachmullen** [comment]
I've changed the scope of this, and it's ready for review. Namely, we now fail catastrophically if plugins fail to load, which is desirable behavior. Aside from that, I also removed the hacked-up extension registry capability. Now the entry point is the exclusive way to load plugins. This gave us the opportunity to remove a fair amount of code.

**Comment by kotfic** [comment]
Oh,  this represents a somewhat big change (failing loudly i mean) will you cut a new minor version once this is in?

**Comment by zachmullen** [comment]
Yes, I plan to cut a release as soon as these two PRs are merged. Thanks!

**Pull request merged**
