### PR TITLE
Use configurable logger rather than raw print()

### PR DESCRIPTION
**Pull request by zachmullen**
Refs #99

Depends on #97

### CODE REVIEW

**Comment by danlamanna** [comment]
Just so I understand, the goal of this is to provide an interface for logging to stdout of the worker node, is this captured within Girder somewhere?

I ask because I had brought up the idea of Girder worker tasks having access to a special `logger` object which would transparently log messages over HTTP(S) to the correct job log in Girder, similar to what we did for https://github.com/OpenGeoscience/geonotebook/pull/68.

**Comment by zachmullen** [comment]
Rebased this now that #97 is merged.

**Comment by mgrauer** [comment]
@zachmullen Can you answer @danlamanna 's question

>Just so I understand, the goal of this is to provide an interface for logging to stdout of the worker node, is this captured within Girder somewhere?

@danlamanna any concerns about merging this, especially from the perspective of attaching log handlers like graylog in the future?

**Comment by zachmullen** [comment]
This is just an attempt to standardize our logging rather than just using print, to make it more extensible in the future. Celery already did this for us to some extent by stealing the standard pipes, but this gives us a bit more control.

@mgrauer you originally opened #99, what did you have in mind?

**Comment by mgrauer** [comment]
I forgot that I opened that.  What I was aiming for was the scope of your work here, a stepping stone that allows configurability to target all messages, instead of "losing" messages to `print`.

**Comment by danlamanna** [comment]
I don't have any concerns.

I'm not entirely familiar with the sort of redirecting of stdout/stderr we're doing inside GW, but does integration with Celery's existing logging infrastructure make sense @zachmullen? Celery offers a way to hook into their global logger, and their per task loggers through [logging-signals](http://docs.celeryproject.org/en/latest/userguide/signals.html#logging-signals). I used them in my throwaway branch testing out graylog [here](https://github.com/girder/girder_worker/commit/d17c40f6b99c1e4cb5609628defe8302db06d6e1).

**Comment by zachmullen** [comment]
It does make sense. That's the sort of work we could do on a future topic once we figure out what we want to do.

**Pull request merged**
