### PR TITLE
Append py27 and py36 coverage

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by zachmullen** [comment]
This is for local testing, I'm assuming?

**Comment by kotfic** [comment]
Addition of the coverage-erase target is for local testing yes. The ```--cov-append``` flag makes sure our coverage reflects coverage from both PY2 and PY3 environments locally and on circle.

**Comment by zachmullen** [comment]
There is divergence in our use of tox between local and CI environments, however that may be an expected thing.

**Comment by kotfic** [comment]
coverage-erase in CI isn't run and the ```--cov-append``` flag in testenv basically does nothing in CI.

**Pull request merged**
