### PR TITLE
Support folder outputs from girder_io

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by cjh1** [comment]
Can we rebase or merge in master to get the idna conflict fix.

**Comment by cjh1** [comment]
Do you think its worth added a mocked out test similar [to this one](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/girder_io/tests/girder_io_test.py#L38)? lgtm either way.

**Comment by zachmullen** [comment]
@cjh1 this is finally ready for review. Not sure why travis is still trying to run it, but it's passing on circle.

**Comment by zachmullen** [comment]
@cjh1 PTAL

**Pull request merged**
